2gua.rainbow-brackets
aaron-bond.better-comments
christian-kohler.path-intellisense
eamodio.gitlens
humao.rest-client
KevinRose.vsc-python-indent
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vsliveshare.vsliveshare
oderwat.indent-rainbow
redhat.vscode-yaml
TabNine.tabnine-vscode
tomoki1207.pdf
usernamehw.errorlens
yzane.markdown-pdf